language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rbennison/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rbennison/docker-react npm run test

